ci: Exclude Spotify plugin based on Rust version
We cannot just do a --exclude gst-plugin-spotify as in the absence of
MSRV being satisfied, anything dependent on cargo metadata fails with
an error like below.

Spotify plugin has MSRV of 1.85 while cargo workspace MSRV is 1.83,
cargo nextest fails pretty early at download stage with an error.

Just nuke Spotify plugin so it is not build or tested with MSRV
specified in root Cargo.toml.

```
error: failed to download `librespot-oauth v0.7.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/core/.cargo/registry/src/index.crates.io-6f17d22bba15001f/librespot-oauth-0.7.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/2538>